# Generated by Django 4.2.3 on 2023-07-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
