# Generated by Django 4.2.3 on 2023-07-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_filmdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmdata',
            name='data',
        ),
        migrations.AddField(
            model_name='filmdata',
            name='actors',
            field=models.CharField(default='Acteurs par défaut', max_length=500),
        ),
        migrations.AddField(
            model_name='filmdata',
            name='box_office',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='filmdata',
            name='genre',
            field=models.CharField(default='Genre par défaut', max_length=100),
        ),
        migrations.AddField(
            model_name='filmdata',
            name='title',
            field=models.CharField(default='Titre par défaut', max_length=200),
        ),
    ]
