# Generated by Django 4.2.3 on 2023-07-24 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_filmdata_confiance_filmdata_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmdata',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
