# Generated by Django 4.2.3 on 2023-08-08 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealFilmData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Titre par défaut', max_length=200)),
                ('box_office', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('genre', models.CharField(default='Genre par défaut', max_length=100)),
                ('actors', models.CharField(default='Acteurs par défaut', max_length=500)),
                ('prediction', models.IntegerField(default=0)),
                ('confiance', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
